- name: Upsource | Check for existing files
  stat:
    path="/opt/upsource"
  register: upsource

- block:

  - name: Upsource | download upsource
    get_url:
      url: http://download.jetbrains.com/upsource/upsource-2017.3.2888.zip 
      dest: /tmp/
      checksum: sha256:17db2853519cbb1d2ac8175cda8b815f4411185677c9f909c69f8b6d1332f60a

  - name: Upsource | unzip source
    unarchive:
      src: /tmp/upsource-2017.3.2888.zip
      dest: /opt
    remote_src: yes

  - name: Upsource | rename directory
    command: mv /opt/upsource-2017.3.2888 /opt/upsource

  - name: Upsource | copy systemd script
    copy: src=upsource.service dest=/etc/systemd/system/upsource.service

  when: not upsource.stat.exists

- name: Upsource | reload systemd
  systemd:
    daemon_reload: yes

- name: Upsource | start upsource
  systemd:
    name: upsource
    state: started
    enabled: yes
