- name: TeamCity | Check for existing files
  stat:
    path="/opt/TeamCity"
  register: teamcity

- name: TeamCity | prepare database
  postgresql_db:
    name: teamcity
    encoding: UTF-8
    login_user: postgres
    login_password: "{{ db_password }}"

- name: TeamCity | add database user
  postgresql_user:
    db: teamcity
    name: teamcity
    password: hHXpa4cGpTdFfSt#
    expires: infinity
    login_user: postgres
    login_password: "{{ db_password }}"
    priv: ALL

- block:

  - name: TeamCity | download TeamCity Files
    get_url:
      url: http://download.jetbrains.com/teamcity/TeamCity-2017.2.3.tar.gz
      dest: /tmp/
      checksum: sha256:29d163f76a9baf1d630d5275765c72b2a085f7537945d7e7b263b54b1ccece47

  - name: TeamCity | extract TeamCity Files
    unarchive: 
      src: /tmp/TeamCity-2017.2.3.tar.gz
      dest: /opt
    remote_src: yes

  - name: TeamCity | copy systemd files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - {src: 'teamcity.service', dest: '/etc/systemd/system/teamcity.service' }
      - {src: 'teamcity-agent.service', dest: '/etc/systemd/system/teamcity-agent.service' }

  when: not teamcity.stat.exists

- name: TeamCity | copy jdbc postgres
  copy: src=postgresql-42.2.2.jar   dest=/opt/TeamCity/data/lib/jdbc/postgresql-42.2.2.jar

- name: TeamCity | reload systemd
  systemd:
    daemon_reload: yes

- name: TeamCity | startup TeamCity
  systemd:
    name: teamcity
    state: started
    enabled: yes

- name: TeamCity | startup TeamCity Agent
  systemd:
    name: teamcity-agent
    state: started
    enabled: yes
