- name: Kibana | add repository
  copy:
    src: kibana.repo 
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0755

- name: Kibana | install kibana
  yum: name={{ item }}
  with_items:
    - kibana
  when: ansible_pkg_mgr == "yum"

- name: Kibana | set node.name
  replace:
      dest: /etc/kibana/kibana.yml
      regexp: '#server.host: "localhost"'
      replace: 'server.host: 127.0.0.1'

- name: Kibana | enable service
  systemd:
    name: kibana
    enabled: yes
    masked: no
