block:
  - name: MariaDB | install
    package:
      name: "{{ item }}"
      state: installed
    with_items:
      - mariadb-server
      - mariadb
      - MySQL-python
  
  - name: Ensure service is started
    service:
      name: mariadb
      state: started
      enabled: yes
  
  - name: Check if root password is set
    shell: >
      mysqladmin -u root status
    changed_when: false
    failed_when: false
    register: root_pwd_check
  
  - name: Set MariaDB root password for the first time
    mysql_user:
      name: root
      password: "{{ mariadb_root_password }}"
      host_all: yes
      state: present
    when: root_pwd_check.rc == 0
when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

