- name: MySQL | Install epel
  yum:
    name=epel-release

- name: MySQL | Install pip
  yum:
    name=python-pip

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: MySQL | Install python libraries
  pip:
    name={{ item }}
  with_items:
    - pexpect
    - psycopg2

- name: MySQL | Install mysql
  yum:
    name=mysql-server
    
- name: MySQL | Setup autostart
  service:
    name=mysqld
    state=started
    enabled=yes
    
- name: MySQL | Harden mysql server
  expect:
    command: mysql_secure_installation
    timeout: 99999
    responses:
      'Enter current password for root \(enter for none\):': ""
      'Set root password\? \[Y\/n\] ': "y"
      'New password': "{{ db_password }}"
      'Re\-enter new password:': "{{ db_password }}"
      'Remove anonymous users\? \[Y\/n\] ': "y"
      'Disallow root login remotely\? \[Y\/n\] ': "y"
      'Remove test database and access to it\? \[Y\/n\] ': "y"
      'Reload privilege tables now\? \[Y\/n\] ': "y"
