- name: Tomcat | check for exist
  stat: path={{ tomcat_home }}
  register: p

- name: Tomcat | create group
  group: name=tomcat
  when: not p.stat.exists

- name: Tomcat | create user
  user: name=tomcat group=tomcat home={{ tomcat_home }} createhome=no
  become: true
  become_method: sudo
  when: not p.stat.exists

- name: Tomcat | download
  get_url: url={{ tomcat_url  }} dest=/tmp/tomcat.tar.gz
  when: not p.stat.exists

- name: Tomcat | extract
  command: chdir=/usr/share /bin/tar xvf /tmp/tomcat.tar.gz -C /opt 
  when: not p.stat.exists

- name: test
  command: ls /opt 
  register: find_result
  when: not p.stat.exists

- name: Tomcat | create home
  command: mv /opt/{{ find_result.stdout }} {{ tomcat_home }}
  when: not p.stat.exists

- name: Tomcat | change ownership
  file: path={{ tomcat_home }} owner=tomcat group=tomcat state=directory recurse=yes
  when: not p.stat.exists

- name: Tomcat | setup service
  copy: src=tomcat.service dest=/etc/systemd/system/ owner=root group=root mode=0755
  when: not p.stat.exists

- name: Ensure directories are 0755
  command: find {{ tomcat_home }} -type d -exec chmod 0755 {} \;
  when: not p.stat.exists

- name: Ensure files are 0644
  command: find {{ tomcat_home }} -type f -exec chmod 0777 {} \;
#  when: not p.stat.exists

- name: Tomcat | Start 
  service: name=tomcat state=started enabled=yes
#  when: not p.stat.exists
