- name: Elasticsearch | download rpm
  get_url:
    url: "{{elastic_rpm}}"
    dest: /tmp/elastic.rpm

- name: Elasticsearch | install elastic
  package: "name=/tmp/elastic.rpm state=installed"

- name: Elasticserach | set node.name
  replace:
      dest: /etc/elasticsearch/elasticsearch.yml
      regexp: '#node.name: node-1'
      replace: 'node.name: elastic-01'

- name: Elasticserach | set cluster.name
  replace:
      dest: /etc/elasticsearch/elasticsearch.yml
      regexp: '#cluster.name: my-application'
      replace: 'cluster.name: elastic-cluster'

- name: Elasticsearch | enable service
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no
