
- name: Docker | Setup repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Docker | Install docker ce
  yum:
    name="{{ item }}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker-ce
