block:
 - name: FHEM | setup repository
   apt_repository:
     repo: deb-src http://debian.fhem.de/nightly/ hardy partner
     state: present

 - name: FHEM | install 
   package:
     name: fhem
     state: present
when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

